### ISSUE TITLE
Interested in consolidating pids to https://github.com/ElectricSidecar/Hyundai-IONIQ-5 ?

### ISSUE THREAD

**Issue by electricsidecar-dev** [Esprit1st/Hyundai-Ioniq-5-Torque-Pro-PIDs#5]
Hello! I'm creating a standardized repository of queryable OBD PIDs in a format that's easily consumable by standard tooling. Reaching out here because this repo seems to be one of many that are documenting the IONIQ 5 pids and I wanted to see if you'd be open to contributing the pids to the OBD database.

You can see examples of some of the pids already discovered in https://github.com/ElectricSidecar/Hyundai-IONIQ-5/blob/main/signalsets/v3/default.json

https://sidecar.clutch.engineering/scanning/extended-pids/

If you have any questions, happy to chat! Can reach me at jeff@clutch.engineering

**Comment by Esprit1st** [comment]
Hi,

I have a couple problems with this.
The data collected here is not mine, it is from people who collected it. So it should stay free.
Second, your project is commercial. Using free data for that doesn't sound right to me.

Thank you very much

**Comment by electricsidecar-dev** [comment]
Agreed that the information should remain free! If you’d be open to chat more I’m working on bringing together a community open source effort around this. Happy to grab a digital coffee to chat.

**Comment by Esprit1st** [comment]
Sure, I'm off work starting Thursday. Any time would work. Any suggestions on how to chat?On Oct 11, 2024 18:26, Electric Sidecar ***@***.***> wrote:
Agreed that the information should remain free! If you’d be open to chat more I’m working on bringing together a community open source effort around this. Happy to grab a digital coffee to chat.

**Comment by electricsidecar-dev** [comment]
Shoot me an email at jeff@clutch.engineering and we can coordinate a Zoom or Google Meet call; whichever is easier for you! Thursday works for me.

**Comment by electricsidecar-dev** [comment]
Very gently following up so that we can schedule time tomorrow! I'm also available Friday :)

**Comment by electricsidecar-dev** [comment]
Hello! I'm free for the next couple of hours if you'd like to chat! If you emailed me I might not know which email it is; if you include Esprit1st in the email I'll be able to find it :)

**Comment by electricsidecar-dev** [comment]
Have to sign off for today, but am free for most of tomorrow :) I'm not sure which time zone you're in, but if you're in closer to GMT or GMT+, I'll also be online later tonight PST.

**Comment by Esprit1st** [comment]
I sent you an email directly to your Jeff-engineering email address. I'm available tomorrow pretty much all day. Not sure where you are located, but I'm on US mountain time. ThanksIngo On Oct 17, 2024 16:03, Electric Sidecar ***@***.***> wrote:
Have to sign off for today, but am free for most of tomorrow :) I'm not sure which time zone you're in, but if you're in closer to GMT or GMT+, I'll also be online later tonight PST.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
On Oct 17, 2024 16:03, Electric Sidecar ***@***.***> wrote:
Have to sign off for today, but am free for most of tomorrow :) I'm not sure which time zone you're in, but if you're in closer to GMT or GMT+, I'll also be online later tonight PST.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
On Oct 17, 2024 16:03, Electric Sidecar ***@***.***> wrote:
Have to sign off for today, but am free for most of tomorrow :) I'm not sure which time zone you're in, but if you're in closer to GMT or GMT+, I'll also be online later tonight PST.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
On Oct 17, 2024 16:03, Electric Sidecar ***@***.***> wrote:
Have to sign off for today, but am free for most of tomorrow :) I'm not sure which time zone you're in, but if you're in closer to GMT or GMT+, I'll also be online later tonight PST.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
On Oct 17, 2024 16:03, Electric Sidecar ***@***.***> wrote:
Have to sign off for today, but am free for most of tomorrow :) I'm not sure which time zone you're in, but if you're in closer to GMT or GMT+, I'll also be online later tonight PST.

**Comment by electricsidecar-dev** [comment]
My inbox is getting a bit flooded right now so I'm not able to find the email because I don't know your name / email 😅😅😅

Let's aim to jump on a Google Meet call tomorrow at 9am PST / 10am MT.

To join the video meeting, click this link: https://meet.google.com/zco-oeby-ycr
Otherwise, to join by phone, dial +1 413-829-4201 and enter this PIN: 244 009 155#
To view more phone numbers, click this link: https://tel.meet/zco-oeby-ycr?hs=5

**Comment by Esprit1st** [comment]
Sounds good. The email I'm using is ***@***.*** ... 😜On Oct 17, 2024 20:50, Electric Sidecar ***@***.***> wrote:
My inbox is getting a bit flooded right now so I'm not able to find the email because I don't know your name / email 😅😅😅
Let's aim to jump on a Google Meet call tomorrow at 9am PST / 10am MT.
To join the video meeting, click this link: https://meet.google.com/zco-oeby-ycr
Otherwise, to join by phone, dial +1 413-829-4201 and enter this PIN: 244 009 155#
To view more phone numbers, click this link: https://tel.meet/zco-oeby-ycr?hs=5

**Comment by electricsidecar-dev** [comment]
lmao every time you reply via email your email gets replaced with `***@***.***` 🤣🤣🤣🤣

**Comment by electricsidecar-dev** [comment]
Getting some serious bash.org flashbacks.

**Comment by Esprit1st** [comment]
Lol. Let's see if this works. My email ***@***.*** Oct 17, 2024 22:25, Electric Sidecar ***@***.***> wrote:
Getting some serious bash.org flashbacks.
